version: 2

sources:
  - name: citibike_source_sql
    schema: citibike_source_sql
    tables:
      - name: src_sql_users
      - name: src_sql_bikes
      - name: src_sql_trips
      - name: src_sql_stations